##############################
# MECHANICS
# Configure the functionality of the plugin.
##############################
mechanics:
  # Whether or not to announce a timer's completion.
  announce-timer-completion: false

  # Whether or not to announce a stopwatch lapping.
  announce-stopwatch-lapping: false

  # Whether or not '/clock reload' will use previously cached
  # seconds/milliseconds or seconds/milliseconds that are stored
  # in the data files.
  # true = previously cached seconds/milliseconds are used.
  # false = file stored seconds/milliseconds are used.
  use-cached-seconds-on-reload: true

##############################
# FORMATTING
# Configure the look of the plugin.
##############################
formatting:
  # Whether or not to place a 0 before single digit numbers.
  # true = 04d 25h 02m 08s
  # false = 4d 25h 2m 8s
  use-leading-zero-for-single-digits: true

  # Message to announce once a timer reaches 0 seconds remaining.
  # Use '{timerName}' for the timer's name.
  # These variables work in-game too! And color codes are supported!
  timer-completion-announcement: "&7Timer &f{timer-name} &7has reached 0 seconds remaining!"

  # Message to announce once a stopwatch laps.
  # Use '{stopwatchName}' for the stopwatch's name.
  # Use '{lapTime}' for the lap timestamp.
  # These variables work in-game too! And color codes are supported!
  stopwatch-lap-announcement: "&7Stopwatch &f{stopwatch-name} &7has lapped at &f{lap-time}&7!"

  # Default formats for timers.
  # Use '{timerName}' for the timer's name.
  # These variables work in-game too! And color codes are supported!
  timer-default-format-prefix: "&b&lTimer: &f"
  timer-default-format-suffix: ""

  # Default formats for stopwatches.
  # Use '{stopwatchName}' for the stopwatch's name.
  # Use '{currentLapTime}' for the current lap time.
  # These variables work in-game too! And color codes are supported!
  stopwatch-default-format-prefix: "&d&lStopwatch: &f"
  stopwatch-default-format-suffix: ""