name: Clock
version: ${project.version}
main: com.luicel.clock.Clock
api-version: 1.16
authors: [ Luicel ]

commands:
  clock:
    usage: /<command>
  timer:
    usage: /<command>
  stopwatch:
    usage: /<command>